// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1cwBcMe2f88phklbSzQlXZ1g73yuxWww',
    appId: '1:620423557693:web:349cb093fa8f6bc1ba7054',
    messagingSenderId: '620423557693',
    projectId: 'sign-up-login-86f97',
    authDomain: 'sign-up-login-86f97.firebaseapp.com',
    storageBucket: 'sign-up-login-86f97.firebasestorage.app',
    measurementId: 'G-S7QBK8CCB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBywvqzQ6e0FA1CwFzVTafVQKQMB3AY4Cs',
    appId: '1:620423557693:android:a897b9eb9f7754eaba7054',
    messagingSenderId: '620423557693',
    projectId: 'sign-up-login-86f97',
    storageBucket: 'sign-up-login-86f97.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1cwBcMe2f88phklbSzQlXZ1g73yuxWww',
    appId: '1:620423557693:web:7d1406cb72ff0e64ba7054',
    messagingSenderId: '620423557693',
    projectId: 'sign-up-login-86f97',
    authDomain: 'sign-up-login-86f97.firebaseapp.com',
    storageBucket: 'sign-up-login-86f97.firebasestorage.app',
    measurementId: 'G-TDDYNMEGBQ',
  );
}
