// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGC8JvqqT1d_0QIOSzci7qowhvV2QzoZ4',
    appId: '1:872003546760:web:bae8219a4dd18e5554f93d',
    messagingSenderId: '872003546760',
    projectId: 'chatapp-d0009',
    authDomain: 'chatapp-d0009.firebaseapp.com',
    storageBucket: 'chatapp-d0009.firebasestorage.app',
    measurementId: 'G-3CCYKT84VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH_nsq9-kXtfXwE5-UIEaN8MQT0jx-HVk',
    appId: '1:872003546760:android:6c209161e25daa0054f93d',
    messagingSenderId: '872003546760',
    projectId: 'chatapp-d0009',
    storageBucket: 'chatapp-d0009.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGC8JvqqT1d_0QIOSzci7qowhvV2QzoZ4',
    appId: '1:872003546760:web:1c7d39dfc339d33c54f93d',
    messagingSenderId: '872003546760',
    projectId: 'chatapp-d0009',
    authDomain: 'chatapp-d0009.firebaseapp.com',
    storageBucket: 'chatapp-d0009.firebasestorage.app',
    measurementId: 'G-L8PJVLJ938',
  );
}
