// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGRL0L2UgkWTlTQkarckLnTC01nmMz9uI',
    appId: '1:151722633142:web:3f5160241f67867289c317',
    messagingSenderId: '151722633142',
    projectId: 'assesmentone-5604a',
    authDomain: 'assesmentone-5604a.firebaseapp.com',
    storageBucket: 'assesmentone-5604a.firebasestorage.app',
    measurementId: 'G-BNYWFYJRND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8-9ZisKoxIBLeiXBNyAQ9V9U12GjEUgU',
    appId: '1:151722633142:android:f4e2e987ca2848f789c317',
    messagingSenderId: '151722633142',
    projectId: 'assesmentone-5604a',
    storageBucket: 'assesmentone-5604a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGRL0L2UgkWTlTQkarckLnTC01nmMz9uI',
    appId: '1:151722633142:web:7dda59af0114585e89c317',
    messagingSenderId: '151722633142',
    projectId: 'assesmentone-5604a',
    authDomain: 'assesmentone-5604a.firebaseapp.com',
    storageBucket: 'assesmentone-5604a.firebasestorage.app',
    measurementId: 'G-Y5PNZ8Z3P5',
  );

}