// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHE9KdLH4BNR17XXzpCkrXb-egmRJJQrU',
    appId: '1:94248904591:web:deb987e704a467f77dcdfa',
    messagingSenderId: '94248904591',
    projectId: 'travelguidance-3098f',
    authDomain: 'travelguidance-3098f.firebaseapp.com',
    storageBucket: 'travelguidance-3098f.firebasestorage.app',
    measurementId: 'G-ZRDL0N3P6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgBfJX5bIjbmZSyVu2DY4a336qF0FK2cA',
    appId: '1:94248904591:android:d3116484915900017dcdfa',
    messagingSenderId: '94248904591',
    projectId: 'travelguidance-3098f',
    storageBucket: 'travelguidance-3098f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHE9KdLH4BNR17XXzpCkrXb-egmRJJQrU',
    appId: '1:94248904591:web:e2239b758686cd9c7dcdfa',
    messagingSenderId: '94248904591',
    projectId: 'travelguidance-3098f',
    authDomain: 'travelguidance-3098f.firebaseapp.com',
    storageBucket: 'travelguidance-3098f.firebasestorage.app',
    measurementId: 'G-X4XBV7MBWF',
  );
}
